T1_1('qubit','q7','biasAmp',[-1000:300:3e4],'biasDelay',16,'time',[0:16*10:20e3],...
      'gui',false,'save',true);

ramsey('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
      'time',[0:16:1e4],'detuning',[50]*1e6,...
      'dataTyp','P','notes','','gui',false,'save',true);
spin_echo('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
      'time',[0:16:2e4],'detuning',[50]*1e6,...
      'notes','','gui',false,'save',true);

ramsey('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
      'time',[0:16:1e4],'detuning',[5]*1e6,...
      'dataTyp','P','notes','','gui',false,'save',true);
spin_echo('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
      'time',[0:16:2e4],'detuning',[5]*1e6,...
      'notes','','gui',false,'save',true);
  
ramsey('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
      'time',[0:16:1e4],'detuning',[5]*1e6,...
      'dataTyp','P','notes','','gui',false,'save',true);
spin_echo('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
      'time',[0:16:2e4],'detuning',[5]*1e6,...
      'notes','','gui',false,'save',true);

  
% ramsey('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
%       'time',[0:16:1e4],'detuning',[3]*1e6,...
%       'dataTyp','P','notes','','gui',false,'save',true);
% spin_echo('qubit','q7','mode','dp',... % available modes are: df01, dp and dz
%       'time',[0:16:2e4],'detuning',[3]*1e6,...
%       'notes','','gui',false,'save',true);

spectroscopy1_zpa_s21('qubit',qubits{8},...
       'biasAmp',[-1e4:1500:3e4],'driveFreq',[5.5e9:0.2e6:5.85e9],...
       'gui',false,'save',true);