%%
    data_taking.public.calibration.iqChnl('awgName','da_ustc_1','chnlSet','C05_2_1','maxSbFreq',400e6,'sbFreqStep',10e6,...
			'loFreqStart',5e9,'loFreqStop',6.1e9,'loFreqStep',100e6,'avgnum',2,...
          'debug',true,'gui',true,'save',true);