%% IQ mixer calibration for 2 channels
    data_taking.public.calibration.iqChnl('awgName','da_ustc_1','chnlSet','C05_2_1','maxSbFreq',300e6,'sbFreqStep',20e6,...
			'loFreqStart',4e9,'loFreqStop',7e9,'loFreqStep',50e6,'avgnum',2,...
          'debug',false,'gui',false,'save',true);