%%
    data_taking.public.calibration.iqChnl('awgName','da_ustc_1','chnlSet','chnlSet1','maxSbFreq',100e6,'sbFreqStep',100e6,...
			'loFreqStart',5.9e9,'loFreqStop',6e9,'loFreqStep',100e6,...
          'gui',true,'save',true);